CREATE TABLE COMANDANTE(COD_COMANDANTE int IDENTITY (1, 1) NOT NULL, USERNAME varchar(8) NOT NULL, PASSWORD char(6) NOT NULL, 
NOME varchar(100) NOT NULL, CONSTRAINT PK_COMANDANTE PRIMARY KEY NONCLUSTERED (COD_COMANDANTE)) 
/*==============================================================*/ CREATE TABLE CONCELHO(COD_CONCELHO int IDENTITY (1, 1) NOT NULL, 
CONCELHO_DESIGN varchar(100) NOT NULL, CONSTRAINT PK_CONCELHO PRIMARY KEY NONCLUSTERED (COD_CONCELHO)) 
/*==============================================================*/ CREATE TABLE CORPFOGO(COD_FOGO int NOT NULL, 
COD_CORPORACAO int NOT NULL, NUM_HOMENS numeric(8, 0) NOT NULL, NUM_VEICULOS numeric(8, 0) NOT NULL, 
CONSTRAINT PK_CORPFOGO PRIMARY KEY NONCLUSTERED (COD_FOGO, COD_CORPORACAO)) 
/*==============================================================*/ CREATE TABLE CORPORACAO(COD_CORPORACAO int IDENTITY (1, 1) NOT NULL,
 CORPORACAO_DESIGN varchar(100) NOT NULL, LATITUDE_CORP float NOT NULL, LONGITUDE_CORP float NOT NULL, NUM_HOMENS_DISP numeric(8, 0) 
NOT NULL, NUM_VEICULOS_DISP numeric(8, 0) NOT NULL, CONSTRAINT PK_CORPORACAO PRIMARY KEY NONCLUSTERED (COD_CORPORACAO)) 
/*==============================================================*/ CREATE TABLE DEPOSITOS(COD_DEPO int IDENTITY (1, 1) NOT NULL, 
COD_TIPO int NOT NULL, LATITUDE float NOT NULL, LONGITUDE float NOT NULL, VOLUME float NOT NULL, 
CONSTRAINT PK_DEPOSITOS PRIMARY KEY NONCLUSTERED (COD_DEPO)) 
/*==============================================================*/ CREATE INDEX DEP_TIPO_FK ON DEPOSITOS(COD_TIPO ASC) 
/*==============================================================*/ CREATE TABLE DISTRITO(COD_DISTRITO int IDENTITY (1, 1) NOT NULL, 
DISTRITO_DESIGN varchar(100) NOT NULL, CONSTRAINT PK_DISTRITO PRIMARY KEY NONCLUSTERED (COD_DISTRITO)) 
/*==============================================================*/ CREATE TABLE ESTADO_FOGO(COD_ESTADO int IDENTITY (1, 1) NOT NULL, 
ESTADO_DESIGN varchar(20) NOT NULL, CONSTRAINT PK_ESTADO_FOGO PRIMARY KEY NONCLUSTERED (COD_ESTADO)) 
/*==============================================================*/ CREATE TABLE FOGO(COD_FOGO int IDENTITY (1, 1) NOT NULL, 
COD_COMANDANTE int NOT NULL, COD_CONCELHO int NOT NULL, COD_RELATORIO int NULL, COD_ESTADO int NOT NULL, LATITUDE_FOGO float NOT NULL, 
LONGITUDE_FOGO float NOT NULL, RAIO_FOGO float NOT NULL, RAIO_SEGURANCA float NOT NULL, DH_START datetime NOT NULL, 
DH_CIRCUNSCRITO datetime NOT NULL, DH_FIM datetime NOT NULL, BAIXAS_BOMBEIROS numeric(8, 0) NOT NULL, BAIXAS_CIVIS numeric(8, 0) NOT NULL, 
CONSTRAINT PK_FOGO PRIMARY KEY NONCLUSTERED (COD_FOGO)) 
/*==============================================================*/ CREATE INDEX RELATORIO_FOGO2_FK ON FOGO(COD_RELATORIO ASC) 
/*==============================================================*/ CREATE INDEX CONCELHO_FOGO_FK ON FOGO(COD_CONCELHO ASC) 
/*==============================================================*/ CREATE INDEX COMANDANTE_FOGO_FK ON FOGO(COD_COMANDANTE ASC) 
/*==============================================================*/ CREATE INDEX FOGO_ESTADO_FK ON FOGO(COD_ESTADO ASC) 
/*==============================================================*/ CREATE TABLE HELI(COD_HELI int IDENTITY (1, 1) NOT NULL, 
HELI_DESIGN varchar(100) NOT NULL, HELI_DISPONIBILIDADE bit NOT NULL, CONSTRAINT PK_HELI PRIMARY KEY NONCLUSTERED (COD_HELI)) 
/*==============================================================*/ CREATE TABLE HELIFOGO(COD_FOGO int NOT NULL, COD_HELI int NOT NULL, 
CONSTRAINT PK_HELIFOGO PRIMARY KEY NONCLUSTERED (COD_FOGO, COD_HELI)) 
/*==============================================================*/ CREATE TABLE RELATORIO(COD_RELATORIO int IDENTITY (1, 1) NOT NULL, 
COD_FOGO int NOT NULL, COMENTARIO varchar(8000) NOT NULL, CONSTRAINT PK_RELATORIO PRIMARY KEY NONCLUSTERED (COD_RELATORIO)) 
/*==============================================================*/ CREATE INDEX RELATORIO_FOGO_FK ON RELATORIO(COD_FOGO ASC) 
/*==============================================================*/ CREATE TABLE TIPOS_DEPOS(COD_TIPO int IDENTITY (1, 1) NOT NULL, 
TIPO_DESIGN varchar(100) NOT NULL, CONSTRAINT PK_TIPOS_DEPOS PRIMARY KEY NONCLUSTERED (COD_TIPO)) 
/*==============================================================*/ CREATE TABLE VOLUNTARIADO(COD_VOLUNTARIO int IDENTITY (1, 1) 
NOT NULL, COD_DISTRITO int NOT NULL, NOME_VOLUNTARIO varchar(100) NOT NULL, NUM_TELEFONE char(9) NOT NULL, EMAIL varchar(50) NOT NULL, 
DISPONIBILIDADE numeric(8, 0) NOT NULL, CONSTRAINT PK_VOLUNTARIADO PRIMARY KEY NONCLUSTERED (COD_VOLUNTARIO)) 
/*==============================================================*/ CREATE INDEX DISTRITO_VOLUNTARIADO_FK ON 
VOLUNTARIADO(COD_DISTRITO ASC)