<?xml version="1.0" encoding="utf-8"?>
<Database Name="BDF" Class="DBLinqDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=.\SQLEXPRESS;AttachDbFilename=&quot;C:\Documents and Settings\Vasco\Os meus documentos\workspace\source\FogUM\FogUM\website\App_Data\BDF.mdf&quot;;Integrated Security=True;User Instance=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="BDFConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.COMANDANTE" Member="COMANDANTEs">
    <Type Name="COMANDANTE">
      <Column Name="COD_COMANDANTE" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="USERNAME" Type="System.String" DbType="VarChar(8) NOT NULL" CanBeNull="false" />
      <Column Name="PASSWORD" Type="System.String" DbType="Char(6) NOT NULL" CanBeNull="false" />
      <Column Name="NOME" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Association Name="COMANDANTE_FOGO" Member="FOGOs" OtherKey="COD_COMANDANTE" Type="FOGO" />
    </Type>
  </Table>
  <Table Name="dbo.VOLUNTARIADO" Member="VOLUNTARIADOs">
    <Type Name="VOLUNTARIADO">
      <Column Name="COD_VOLUNTARIO" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="COD_DISTRITO" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="NOME_VOLUNTARIO" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="NUM_TELEFONE" Type="System.String" DbType="Char(9) NOT NULL" CanBeNull="false" />
      <Column Name="EMAIL" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="DISPONIBILIDADE" Type="System.Decimal" DbType="Decimal(8,0) NOT NULL" CanBeNull="false" />
      <Association Name="DISTRITO_VOLUNTARIADO" Member="DISTRITO" ThisKey="COD_DISTRITO" Type="DISTRITO" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.CONCELHO" Member="CONCELHOs">
    <Type Name="CONCELHO">
      <Column Name="COD_CONCELHO" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="CONCELHO_DESIGN" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Association Name="CONCELHO_FOGO" Member="FOGOs" OtherKey="COD_CONCELHO" Type="FOGO" />
    </Type>
  </Table>
  <Table Name="dbo.CORPFOGO" Member="CORPFOGOs">
    <Type Name="CORPFOGO">
      <Column Name="COD_FOGO" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="COD_CORPORACAO" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="NUM_HOMENS" Type="System.Decimal" DbType="Decimal(8,0) NOT NULL" CanBeNull="false" />
      <Column Name="NUM_VEICULOS" Type="System.Decimal" DbType="Decimal(8,0) NOT NULL" CanBeNull="false" />
      <Association Name="CORPORACAO_CORPFOGO" Member="CORPORACAO" ThisKey="COD_CORPORACAO" Type="CORPORACAO" IsForeignKey="true" />
      <Association Name="FOGO_CORPFOGO" Member="FOGO" ThisKey="COD_FOGO" Type="FOGO" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.CORPORACAO" Member="CORPORACAOs">
    <Type Name="CORPORACAO">
      <Column Name="COD_CORPORACAO" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="CORPORACAO_DESIGN" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="DISPONIBILIDADE_CORP" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="LATITUDE_CORP" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="LONGITUDE_CORP" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="NUM_HOMENS_DISP" Type="System.Decimal" DbType="Decimal(8,0) NOT NULL" CanBeNull="false" />
      <Column Name="NUM_VEICULOS_DISP" Type="System.Decimal" DbType="Decimal(8,0) NOT NULL" CanBeNull="false" />
      <Association Name="CORPORACAO_CORPFOGO" Member="CORPFOGOs" OtherKey="COD_CORPORACAO" Type="CORPFOGO" />
    </Type>
  </Table>
  <Table Name="dbo.DEPOSITOS" Member="DEPOSITOs">
    <Type Name="DEPOSITO">
      <Column Name="COD_DEPO" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="COD_TIPO" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="LATITUDE" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="LONGITUDE" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="VOLUME" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Association Name="TIPOS_DEPO_DEPOSITO" Member="TIPOS_DEPO" ThisKey="COD_TIPO" Type="TIPOS_DEPO" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.DISTRITO" Member="DISTRITOs">
    <Type Name="DISTRITO">
      <Column Name="COD_DISTRITO" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="DISTRITO_DESIGN" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Association Name="DISTRITO_VOLUNTARIADO" Member="VOLUNTARIADOs" OtherKey="COD_DISTRITO" Type="VOLUNTARIADO" />
    </Type>
  </Table>
  <Table Name="dbo.ESTADO_FOGO" Member="ESTADO_FOGOs">
    <Type Name="ESTADO_FOGO">
      <Column Name="COD_ESTADO" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ESTADO_DESIGN" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Association Name="ESTADO_FOGO_FOGO" Member="FOGOs" OtherKey="COD_ESTADO" Type="FOGO" />
    </Type>
  </Table>
  <Table Name="dbo.FOGO" Member="FOGOs">
    <Type Name="FOGO">
      <Column Name="COD_FOGO" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="COD_COMANDANTE" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="COD_CONCELHO" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="COD_RELATORIO" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="COD_ESTADO" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="LATITUDE_FOGO" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="LONGITUDE_FOGO" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="RAIO_FOGO" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="RAIO_SEGURANCA" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="DH_START" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="DH_CIRCUNSCRITO" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="DH_FIM" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="BAIXAS_BOMBEIROS" Type="System.Decimal" DbType="Decimal(8,0) NOT NULL" CanBeNull="false" />
      <Column Name="BAIXAS_CIVIS" Type="System.Decimal" DbType="Decimal(8,0) NOT NULL" CanBeNull="false" />
      <Association Name="FOGO_CORPFOGO" Member="CORPFOGOs" OtherKey="COD_FOGO" Type="CORPFOGO" />
      <Association Name="FOGO_HELIFOGO" Member="HELIFOGOs" OtherKey="COD_FOGO" Type="HELIFOGO" />
      <Association Name="FOGO_RELATORIO" Member="RELATORIOs" OtherKey="COD_FOGO" Type="RELATORIO" />
      <Association Name="COMANDANTE_FOGO" Member="COMANDANTE" ThisKey="COD_COMANDANTE" Type="COMANDANTE" IsForeignKey="true" />
      <Association Name="CONCELHO_FOGO" Member="CONCELHO" ThisKey="COD_CONCELHO" Type="CONCELHO" IsForeignKey="true" />
      <Association Name="ESTADO_FOGO_FOGO" Member="ESTADO_FOGO" ThisKey="COD_ESTADO" Type="ESTADO_FOGO" IsForeignKey="true" />
      <Association Name="RELATORIO_FOGO" Member="RELATORIO" ThisKey="COD_RELATORIO" Type="RELATORIO" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.HELI" Member="HELIs">
    <Type Name="HELI">
      <Column Name="COD_HELI" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="HELI_DESIGN" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="HELI_DISPONIBILIDADE" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="HELI_HELIFOGO" Member="HELIFOGOs" OtherKey="COD_HELI" Type="HELIFOGO" />
    </Type>
  </Table>
  <Table Name="dbo.HELIFOGO" Member="HELIFOGOs">
    <Type Name="HELIFOGO">
      <Column Name="COD_FOGO" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="COD_HELI" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="HELI_HELIFOGO" Member="HELI" ThisKey="COD_HELI" Type="HELI" IsForeignKey="true" />
      <Association Name="FOGO_HELIFOGO" Member="FOGO" ThisKey="COD_FOGO" Type="FOGO" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.RELATORIO" Member="RELATORIOs">
    <Type Name="RELATORIO">
      <Column Name="COD_RELATORIO" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="COD_FOGO" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="COMENTARIO" Type="System.String" DbType="VarChar(8000) NOT NULL" CanBeNull="false" />
      <Association Name="RELATORIO_FOGO" Member="FOGOs" OtherKey="COD_RELATORIO" Type="FOGO" />
      <Association Name="FOGO_RELATORIO" Member="FOGO" ThisKey="COD_FOGO" Type="FOGO" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.TIPOS_DEPOS" Member="TIPOS_DEPOs">
    <Type Name="TIPOS_DEPO">
      <Column Name="COD_TIPO" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TIPO_DESIGN" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Association Name="TIPOS_DEPO_DEPOSITO" Member="DEPOSITOs" OtherKey="COD_TIPO" Type="DEPOSITO" />
    </Type>
  </Table>
</Database>